# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Storkks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
platform :ios, '8.0'
pod 'SDWebImage', '~> 4.0'
pod 'ZVProgressHUD', :git => 'https://github.com/zevwings/ZVProgressHUD.git'

  # Pods for Storkks

  target 'StorkksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StorkksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
